clean: true
module: Venice
author: Zewo
author_url: http://zewo.io
github_url: https://github.com/Zewo/Venice
swift_version: 3.1
xcodebuild_arguments:
  - -scheme
  - Venice

custom_categories:
  - name: Coroutines
    children:
    - Coroutine

  - name: Channels
    children:
    - Channel

  - name: File Descriptors
    children:
    - FileDescriptor
    
  - name: Time
    children:
    - Duration
    - Deadline
    - Int

  - name: Handles
    children:
    - Handle

  - name: Errors
    children:
    - VeniceError
