os:
  - linux
  - osx
language: generic
sudo: false
dist: trusty
osx_image: xcode8.3
addons:
  apt:
    sources:
      - sourceline: 'deb [trusted=yes] http://apt.zewo.io ./'
    packages:
      - libdill
install:
  - eval "$(curl -sL http://sh.zewo.io/install-libdill.sh)"
script:
  - bash <(curl -sL http://sh.zewo.io/build.sh)
