notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install zewo/tap/libdill; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git clone https://github.com/Zewo/libdill; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd libdill; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./autogen.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./configure; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo make install; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd ..; fi
  - echo $LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=/usr/local/lib
  - echo $LD_LIBRARY_PATH
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/Travis/install.sh)"
script:
  - bash <(curl -s https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/Travis/build-test.sh) Venice
after_success:
  - bash <(curl -s https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/Travis/report-coverage.sh)
